include $(GOROOT)/src/Make.inc

TARG=telblog
GOFILES=\
	htmlstrip.go\
	wrap.go\
	db.go\
	mongo_db.go\
	post.go\
	blog.go\
	commands.go\
	session.go\
	server.go\
	main.go

include $(GOROOT)/src/Make.cmd
