include $(GOROOT)/src/Make.inc

TARG=telblog
GOFILES=\
	../shared/telstrip.go\
	../shared/htmlstrip.go\
	wrap.go\
	../shared/db.go\
	../shared/mongo_db.go\
	../shared/post.go\
	blog.go\
	commands.go\
	session.go\
	server.go\
	main.go

include $(GOROOT)/src/Make.cmd
