include $(GOROOT)/src/Make.inc

TARG=blog
GOFILES=\
	../shared/htmlstrip.go\
	../shared/post.go\
	../shared/db.go\
	../shared/mongo_db.go\
	index.go\
	admin.go\
	css.go\
	rss.go\
	main.go

include $(GOROOT)/src/Make.cmd
